In [2]:
import pandas as pd
import numpy as np

In [3]:
with open('LiterallyWikidata/files_needed/attribute.txt','r') as fr:
    attributes = [line.strip() for line in fr] 
dict_att_2_idx = dict(zip(attributes, np.arange(0, len(attributes), 1)))

## constraint needed:
pop_idx = dict_att_2_idx ['P1082']
gdp = dict_att_2_idx ['P4010']
nominal_gdp = dict_att_2_idx ['P2131']
nominal_gdp_per = dict_att_2_idx ['P2132']
gdp_per = dict_att_2_idx ['P2299']
date_of_birth = dict_att_2_idx ['P569']
date_of_death = dict_att_2_idx ['P570']
area = dict_att_2_idx['P2046']
work_end = dict_att_2_idx['P2032']
work_start = dict_att_2_idx['P2031']
height= dict_att_2_idx['P2048']
Latitude = dict_att_2_idx['P625_Latitude']
Longtiude = dict_att_2_idx['P625_Longtiude']
list_var=[pop_idx,gdp,gdp_per,date_of_birth,date_of_death,area,work_start,work_end,height,Latitude,Longtiude] 
print('pop_idx,gdp,gdp_per,date_of_birth,date_of_death,area,work_start,work_end,height,Latitude,Longtiude',list_var)
def read_result (filepath):
    return pd.read_csv(filepath)

def var_r_df (df,var=list_var):
    #還可以增加
    list_var = var
    df = df[df.a.isin(list_var)].sort_values(by='a')
    df['mae']=abs(df.pred_h-df.target_h)
    df['square_mae']=np.square(abs(df.pred_h-df.target_h))
    return df

pop_idx,gdp,gdp_per,date_of_birth,date_of_death,area,work_start,work_end,height,Latitude,Longtiude [0, 25, 20, 195, 196, 2, 200, 201, 4, 226, 233]

In [5]:
attri_data = pd.read_csv('/projekte/tcl/tclext/kgc/LiterallyWikidata/files_needed/numeric_literals_ver06')

In [29]:
df=read_result('exp_cons/predicted_result/vargap_10_200_128_64preds_att_head.csv')
# print(df[:20])
# print('diff a len', len(df.a.unique()))
df=var_r_df(df)
#print(df[:40])
#print(df.a.value_counts())
df_preds=df[df['pred_h']<0.0]
df_a25=df[df['a']==25]
#print('number of pred == 1 is ',len(df_preds))
print(df_preds)
#print(df[:10])
print(f'------------preds a mae--------------------')
print(df.groupby('a').mae.agg('mean'))
print(f'------------preds a rmse--------------------')
square_v = df.groupby('a').square_mae.agg('mean')
print(np.sqrt(square_v))

233.0    2496
226.0    2495
2.0      2175
0.0      2144
195.0    1593
4.0       778
200.0     705
196.0     505
201.0     330
20.0       16
25.0       16
Name: a, dtype: int64
         idx        e      a    pred_h  target_h       mae  square_mae
19953  19953  28058.0    2.0 -0.972328 -0.006846  0.965481    0.932154
8364    8364  55757.0    2.0 -0.949305 -0.006852  0.942453    0.888218
20137  20137  11063.0    2.0 -0.052527 -0.006852  0.045675    0.002086
16424  16424   5423.0    2.0 -0.975806 -0.006852  0.968954    0.938872
13639  13639  47234.0    2.0 -0.976212 -0.006852  0.969360    0.939659
...      ...      ...    ...       ...       ...       ...         ...
9039    9039  14443.0  233.0 -0.935885 -1.691451  0.755567    0.570881
25369  25369  41456.0  233.0 -0.664995  0.234039  0.899034    0.808262
21964  21964  44001.0  233.0 -0.538297  0.195966  0.734263    0.539142
25351  25351  34873.0  233.0 -0.952279 -1.553279  0.601000    0.361201
2          2  23046.0  233.0 -0.515147  0.175239  0.690387    0.476634

[4810 rows x 7 columns]
------------preds a mae--------------------
a
0.0      1.041543
2.0      0.879488
4.0      0.690150
20.0     1.143733
25.0     2.023631
195.0    0.695148
196.0    0.756382
200.0    0.690643
201.0    0.787440
226.0    0.957390
233.0    1.050784
Name: mae, dtype: float64
------------preds a rmse--------------------
a
0.0      1.359616
2.0      0.891211
4.0      0.747391
20.0     1.234514
25.0     2.753384
195.0    1.135832
196.0    1.361828
200.0    0.953192
201.0    1.112925
226.0    1.232856
233.0    1.236392
Name: square_mae, dtype: float64

In [13]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler
# inverse_transform
def v_scale(attdf):
    scaler = StandardScaler().fit(attdf['v'].to_numpy().reshape(-1,1))
    return scaler
alist=list(attri_data['a'].unique())
pred_real={}
for a_name in alist:
    attdf = attri_data[attri_data["a"]==a_name]
    df['predsreal']= v_scale(attdf).inverse_transform(df.pred_h.to_numpy().reshape(-1,1))

In [27]:
df[df.a==25.0]

         idx        e     a    pred_h  target_h       mae  square_mae
24120  24120  55606.0  25.0  0.329871  0.001464  0.328407    0.107851
20288  20288  17051.0  25.0  0.323208  0.001906  0.321302    0.103235
4914    4914  47485.0  25.0  0.337120  0.492513  0.155393    0.024147
10663  10663  12605.0  25.0  0.382568  0.003292  0.379276    0.143851
14941  14941  54112.0  25.0  0.287244  0.789867  0.502623    0.252630
10278  10278  53849.0  25.0  0.244628  0.015303  0.229326    0.052590
18791  18791   3246.0  25.0  0.269504  0.006659  0.262844    0.069087
582      582  56232.0  25.0  0.403984  0.003601  0.400382    0.160306
21014  21014    300.0  25.0  0.303297  0.000334  0.302963    0.091787
15033  15033    948.0  25.0  0.367414  0.000033  0.367381    0.134969
22826  22826  48627.0  25.0  0.324642  0.000008  0.324635    0.105388
5117    5117  53134.0  25.0  0.239352  0.004305  0.235047    0.055247
4258    4258  23513.0  25.0  0.411750  1.000000  0.588250    0.346038
277      277  54425.0  25.0  0.336062  0.004062  0.332000    0.110224
12370  12370  48219.0  25.0  0.268941  0.000043  0.268897    0.072306
5610    5610  48829.0  25.0  0.360085  0.000018  0.360067    0.129648

In [25]:
min(df.mae)

1.8781245469946458e-05